#!/usr/bin/env sh

if [ "$(id -u)" -eq 0 ]; then
  echo "This script cannot be run as root. It will call sudo as needed"
  exit 1
fi

set -e

###
# UTILS & VARS
###

BOLD="\033[0;1m"
GREEN="\033[0;32m"
BOLD_GREEN="\033[1;32m"
RESET="\033[0m"

DIR_NAME="$(realpath "$(dirname "$0")")"
PACKAGES_DIR="$DIR_NAME/packages"
FLATPAK_APPS="$(cat "$PACKAGES_DIR/flatpak-apps")"

print_title() {
  printf "%b==>%b %b%s%b\n" "$BOLD_GREEN" "$RESET" "$BOLD" "$1" "$RESET"
}

print_sub_title() {
  printf "%b=>%b %s\n" "$GREEN" "$RESET" "$1"
}

###
# STEPS
###

install_nix_step() {
  print_title "Setup nix"

  if command -v nix > /dev/null 2>&1; then
    print_sub_title "Nix already installed, skipping installation"
  else
    (set -x; curl -L https://nixos.org/nix/install | sh -s -- --no-daemon --yes --no-modify-profile)

    # shellcheck disable=SC1091
    . "$HOME"/.nix-profile/etc/profile.d/nix.sh

    (set -x; nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager)
    (set -x; nix-channel --add https://github.com/nix-community/nixGL/archive/main.tar.gz nixgl)
    (set -x; nix-channel --update)
    (set -x; nix-channel --list)
  fi

  if command -v home-manager > /dev/null 2>&1; then
    print_sub_title "Home-manager already installed, skipping installation"
  else
    (set -x; nix-shell '<home-manager>' -A install)
  fi

  (set -x; mkdir -p "$HOME"/.config/home-manager)

  if [ -f "$HOME"/.config/home-manager/home.nix ]; then
    (set -x; rm "$HOME"/.config/home-manager/home.nix)
  fi

  (set -x; ln -s "$HOME"/.dotfiles/nix/home.nix "$HOME"/.config/home-manager/home.nix)
  (set -x; home-manager switch -b backup)
  (set -x; nix-collect-garbage -d)
}

install_eget_packages_step() {
  print_title "Install eget packages"

  if ! command -v eget > /dev/null 2>&1; then
    print_sub_title "Eget is not installed, skipping"

    return
  fi

  if [ -z "$(cat "$PACKAGES_DIR/eget-executables")" ]; then
    print_sub_title "No eget packages to install, skipping"

    return
  fi

  while IFS= read -r executable; do
    if [ -n "$executable" ]; then
      clean_executable="$(echo "$executable" | sed 's/#disable-upgrade//g')"

      # shellcheck disable=SC2086
      (set -x; eget $clean_executable --upgrade-only)
    fi
  done < "$PACKAGES_DIR/eget-executables"
  echo

  print_sub_title "Add mise completions & install deps"
  (set -x; mkdir -p "$HOME"/.config/fish/completions)
  (set -x; mkdir -p "$HOME"/.local/share/bash-completion/completions)
  (set -x; "$HOME"/.local/bin/mise completion fish > "$HOME"/.config/fish/completions/mise.fish)
  (set -x; "$HOME"/.local/bin/mise completion bash > "$HOME"/.local/share/bash-completion/completions/mise.bash)
  (set -x; "$HOME"/.local/bin/mise install)
}

install_flatpak_apps_and_runtimes_step() {
  print_title "Install flatpak apps and runtimes"

  if ! command -v flatpak > /dev/null 2>&1; then
    print_sub_title "Flatpak is not installed, skipping"

    return
  fi

  if [ -z "$FLATPAK_APPS" ]; then
    print_sub_title "No flatpak apps to install, skipping instalation"
  else
    # shellcheck disable=SC2086
    (set -x; flatpak install -y --noninteractive $FLATPAK_APPS)
  fi

  if [ -z "$(cat "$PACKAGES_DIR/flatpak-runtimes")" ]; then
    print_sub_title "No flatpak runtimes to install, skipping instalation"
  else
    # shellcheck disable=SC2046
    (set -x; flatpak install -y --noninteractive $(cat "$PACKAGES_DIR/flatpak-runtimes"))
  fi
}

###
# MAIN
###

install_nix_step
echo

install_eget_packages_step
echo

install_flatpak_apps_and_runtimes_step
echo

printf "%b✓%b All done, restart and open a new shell to get started !!!\n" "$GREEN" "$RESET"
