#!/usr/bin/env sh

set -e

# shellcheck source=/dev/null
. "$(dirname "$0")"/../../utils.sh

if [ "$(id -u)" -eq 0 ]; then
  log_error "This script cannot be run as root. It will call sudo as needed"
  exit 1
fi

log_info "Running arch steps"

for step in "$DOTFILES_DIR"/src/os/arch/steps/*.sh; do
  log_info "Running step \"$(basename "$step")\""
  # shellcheck source=/dev/null
  . "$step"
done

. "$DOTFILES_DIR"/src/os/common/setup.sh

log_success "All done, restart your computer."
