#!/usr/bin/env sh

set -e

ROOT_DIR="$(cd "$(dirname "$0")" && cd .. && pwd)"
SH_FILES="$(shfmt -f "$ROOT_DIR")"

echo "=> Running shellcheck"
# shellcheck disable=SC2086
(
  set -x
  shellcheck -f tty --norc -s sh $SH_FILES
)
echo
