#!/usr/bin/env sh

set -e

ROOT_DIR="$(cd "$(dirname "$0")" && cd .. && pwd)"
SH_FILES="$(shfmt -f "$ROOT_DIR")"
NIX_FILES="$(find "$ROOT_DIR" -type f -name "*.nix")"

echo "=> Running shellcheck"
(
  set -x
  # shellcheck disable=SC2086
  shellcheck -f tty --norc -s sh $SH_FILES
)
echo

echo "=> Running statix"
(
  set -x
  # shellcheck disable=SC2086
  statix check $ROOT_DIR
)
echo

echo "=> Running deadnix"
(
  set -x
  # shellcheck disable=SC2086
  deadnix -f -o human-readable $NIX_FILES
)
echo
