#!/usr/bin/env sh

set -e

# shellcheck source=/dev/null
. "$(dirname "$0")"/utils.sh

if [ "$(id -u)" -eq 0 ]; then
  log_error "This script cannot be run as root. It will call sudo as needed"
  exit 1
fi

log_info "Upgrade and install os packages"
sudo pacman -Syyuu
sudo pacman -S --needed --noconfirm \
  linux-firmware base-devel \
  \
  intel-media-driver vulkan-intel libvpl vpl-gpu-rt libvdpau-va-gl \
  \
  nvidia-open nvidia-open-lts nvidia-utils libva-nvidia-driver \
  \
  gst-libav gst-plugin-va gst-plugins-bad gst-plugins-base gst-plugins-good gst-plugins-ugly gst-plugin-pipewire \
  \
  adw-gtk-theme gnome-console gnome-backgrounds libedataserverui4 folks bazaar \
  \
  intel-gpu-tools nvtop libva-utils vdpauinfo vulkan-mesa-layers vulkan-tools \
  \
  ffmpeg gufw code flatpak bash-completion curl file git procps-ng \
  ttf-cascadia-code ttf-cascadia-code-nerd ttf-cascadia-mono-nerd \
  act bat-extras bat bitwarden-cli btop git-delta dive docker docker-buildx eza fastfetch fish hyperfine \
  jq k9s kubectl micro mise oha podman rsync syncthing tealdeer tokei wget go-yq yt-dlp wl-clipboard dra usage

if ! systemctl is-active --quiet bluetooth; then
  log_info "Enable bluetooth service"
  systemctl enable --now bluetooth
fi

if ! systemctl is-active --quiet ufw; then
  log_info "Enable ufw service"
  systemctl enable --now ufw
fi

if sudo ufw status | grep -q "inactive"; then
  log_info "Enable ufw"
  sudo ufw enable
fi

log_info "Add localsend to firewall exclusion"
sudo ufw allow "53317/udp"
sudo ufw allow "53317/tcp"

log_info "Add syncthing to firewall exclusion"
sudo ufw allow syncthing

log_info "Early KMS nvidia & intel"
printf "hostonly=\"yes\"\\ncompress=\"lz4\"\\nforce_drivers+=\" i915 nvidia nvidia_modeset nvidia_uvm nvidia_drm \"" | sudo tee "/etc/dracut.conf.d/myflags.conf" > /dev/null
sudo reinstall-kernels

log_success "OS setup completed."
