#!/usr/bin/env sh

set -e

# shellcheck source=/dev/null
. "$(dirname "$0")"/utils.sh

if [ "$(id -u)" -eq 0 ]; then
  log_error "This script cannot be run as root. It will call sudo as needed"
  exit 1
fi

log_info "Set gnome & gnome apps configs"
gsettings set "org.gnome.mutter" "experimental-features" "['variable-refresh-rate', 'scale-monitor-framebuffer', 'xwayland-native-scaling']"

gsettings set "org.gnome.desktop.interface" "gtk-theme" "adw-gtk3-dark"
gsettings set "org.gnome.desktop.interface" "color-scheme" "prefer-dark"
gsettings set "org.gnome.desktop.interface" "accent-color" "orange"
gsettings set "org.gnome.desktop.interface" "monospace-font-name" "Cascadia Code 10"

gsettings set "org.gnome.settings-daemon.plugins.color" "night-light-enabled" "true"
gsettings set "org.gnome.settings-daemon.plugins.color" "night-light-temperature" "2500"
gsettings set "org.gnome.settings-daemon.plugins.color" "night-light-schedule-automatic" "false"
gsettings set "org.gnome.settings-daemon.plugins.color" "night-light-schedule-from" "18.0"
gsettings set "org.gnome.settings-daemon.plugins.color" "night-light-schedule-to" "9.0"

gsettings set "org.gnome.Console" "theme" "auto"
gsettings set "org.gnome.Console" "shell" "['/home/linuxbrew/.linuxbrew/bin/fish']"

gsettings set "org.gnome.desktop.background" "picture-uri" "file:///usr/share/backgrounds/gnome/blobs-l.svg"
gsettings set "org.gnome.desktop.background" "picture-uri-dark" "file:///usr/share/backgrounds/gnome/blobs-d.svg"

gsettings set "org.gnome.desktop.wm.preferences" "button-layout" "appmenu:minimize,maximize,close"

gsettings set "org.gnome.mutter" "center-new-windows" "true"

gsettings set "org.gnome.desktop.interface" "gtk-enable-primary-paste" "false"

gsettings set "org.gnome.desktop.search-providers" "enabled" "['org.gnome.Calendar.desktop', 'org.gnome.Calculator.desktop', 'org.gnome.Contacts.desktop']"
gsettings set "org.gnome.desktop.search-providers" "disabled" "[]"

log_warning "GNOME: Set the legacy gtk theme using gnome-tweaks"
# Install https://github.com/mukul29/legacy-theme-auto-switcher-gnome-extension manually
log_warning "GNOME: \`legacy-theme-auto-switcher-gnome-extension\` must be setup manually"

# log_info "Setup flatpak remotes"
flatpak remote-add --user --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak remote-modify --user --enable flathub-beta
flatpak remote-modify --user --enable flathub

log_info "Install flatpak runtimes & apps"
flatpak install --user -y --noninteractive flathub \
  org.gtk.Gtk3theme.adw-gtk3 \
  org.gtk.Gtk3theme.adw-gtk3-dark \
  app.drey.KeyRack ca.desrt.dconf-editor com.bitwarden.desktop \
  com.brave.Browser com.discordapp.Discord com.github.Matoking.protontricks \
  com.github.neithern.g4music com.github.tchx84.Flatseal com.mattjakeman.ExtensionManager \
  com.usebottles.bottles com.valvesoftware.Steam com.vysp3r.ProtonPlus \
  io.gitlab.news_flash.NewsFlash net.nokyan.Resources \
  org.gnome.Boxes org.gnome.Calculator org.gnome.Calendar org.gnome.Contacts \
  org.gnome.Loupe org.gnome.Papers io.github.diegopvlk.Cine org.gnome.TextEditor \
  org.gnome.seahorse.Application org.libreoffice.LibreOffice org.localsend.localsend_app \
  org.mozilla.firefox org.prismlauncher.PrismLauncher org.raspberrypi.rpi-imager

if ! command -v brew > /dev/null 2>&1; then
  log_info "Setup brew"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  /home/linuxbrew/.linuxbrew/bin/brew analytics off
fi

log_info "Install brew packages"
/home/linuxbrew/.linuxbrew/bin/brew bundle check --file "$(dirname "$0")/brew-packages" || /home/linuxbrew/.linuxbrew/bin/brew bundle install --cleanup --file "$(dirname "$0")/brew-packages"

log_info "Setup dotfiles & configs"
"$(dirname "$0")"/../home/.local/bin/dots apply

log_info "Enable syncthing service"
/home/linuxbrew/.linuxbrew/bin/brew services start syncthing

log_info "Mask gnome ssh agent"
systemctl --user mask gcr-ssh-agent.service
systemctl --user mask gcr-ssh-agent.socket

log_success "User setup completed."
