#!/usr/bin/env sh

set -e

# shellcheck source=/dev/null
. "$(dirname "$0")"/utils.sh

if [ "$(id -u)" -eq 0 ]; then
  log_error "This script cannot be run as root. It will call sudo as needed"
  exit 1
fi

log_info "Upgrade and install os packages"
sudo pacman -Syyuu
sudo pacman -S --needed --noconfirm \
  linux-firmware \
  \
  intel-media-driver \
  libvdpau-va-gl \
  vpl-gpu-rt \
  vulkan-intel libvpl \
  \
  libva-nvidia-driver \
  nvidia-open \
  nvidia-open-lts \
  nvidia-utils \
  \
  gst-libav \
  gst-plugin-gtk4 \
  gst-plugin-pipewire \
  gst-plugin-va \
  gst-plugins-bad \
  gst-plugins-base \
  gst-plugins-good \
  gst-plugins-ugly \
  \
  adw-gtk-theme \
  bazaar \
  folks \
  gnome-backgrounds \
  gnome-console \
  libedataserverui4 \
  \
  intel-gpu-tools \
  libva-utils \
  vdpauinfo \
  vulkan-mesa-layers \
  vulkan-tools \
  \
  bash-completion \
  flatpak \
  glib2 \
  gufw \
  wl-clipboard

if ! systemctl is-active --quiet bluetooth; then
  log_info "Enable bluetooth service"
  systemctl enable --now bluetooth
fi

if ! systemctl is-active --quiet ufw; then
  log_info "Enable ufw service"
  systemctl enable --now ufw
fi

if sudo ufw status | grep -q "inactive"; then
  log_info "Enable ufw"
  sudo ufw enable
fi

log_info "Add localsend to firewall exclusion"
sudo ufw allow "53317/udp"
sudo ufw allow "53317/tcp"

log_info "Add syncthing to firewall exclusion"
sudo ufw allow "22000/udp"
sudo ufw allow "21027/udp"

log_info "Early KMS nvidia & intel"
printf "hostonly=\"yes\"\\ncompress=\"lz4\"\\nforce_drivers+=\" i915 nvidia nvidia_modeset nvidia_uvm nvidia_drm \"" | sudo tee "/etc/dracut.conf.d/myflags.conf" > /dev/null
sudo reinstall-kernels

log_info "Enable deep sleep"
sudo mkdir -p /etc/systemd/sleep.conf.d
printf "[Sleep]\nMemorySleepMode=deep" | sudo tee "/etc/systemd/sleep.conf.d/mem-deep.conf" > /dev/null
systemctl daemon-reload

log_success "OS setup completed."
