---
name: CI

on:
  - push
  - pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@v2
        with:
          install: true
          cache: true

      - name: check formatting
        run: ./.bin/check-fmt

      - name: check linting
        run: ./.bin/check-lint
